services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: {{POSTGRES_PASSWORD}}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    networks:
      - matrix_network

  valkey:
    image: valkey/valkey:8-alpine
    restart: unless-stopped
    command: valkey-server --save 900 1 --save 300 10 --save 60 10000
    volumes:
      - valkey_data:/data:Z
    networks:
      - matrix_network

  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - valkey
    environment:
      SYNAPSE_SERVER_NAME: matrix.tantalius.com
      SYNAPSE_REPORT_STATS: "no"
    volumes:
      - ./synapse:/data:Z
      - ./synapse/homeserver.yaml:/data/homeserver.yaml:ro,z
      - ./synapse/log.config:/data/log.config:ro,z
    networks:
      - matrix_network
    ports:
      - "8008:8008"

  cinny:
    build:
      context: ./cinny
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - matrix_network
    ports:
      - "8082:80"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - synapse
      - cinny
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
    networks:
      - matrix_network
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:
  valkey_data:

networks:
  matrix_network:
    driver: bridge
